### ISSUE TITLE
Alignment of images in text

### ISSUE THREAD

**Issue by J0000** [humhub/humhub-prosemirror#10]
It would be cool have the possibility to set an alignment for inserted images. Perhaps realized with CSS-float? The Image-Setting dialogue could have an additional dropdown with left/right to set the option

**Comment by buddh4** [comment]
We should may consider one of the mentioned solutions at https://stackoverflow.com/questions/255170/markdown-and-image-alignment

**Comment by luke-** [comment]
To directly support some basic html?
