### ISSUE TITLE
Header anchors lost

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub-prosemirror#113]
Problem from here https://github.com/humhub/wiki-2.0-issues/issues/49#issuecomment-1630820696:

- here https://github.com/humhub/humhub-prosemirror/commit/1ff86325c0e6c7f7771d1d2842491d442270c262#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L36, the package `markdown-it-anchor` was updated from version `6.0.1` to `8.6.7`
- https://www.npmjs.com/package/markdown-it-anchor?activeTab=readme#permalinks -> "Version 8.0.0 completely reworked the way permalinks work in order to offer more accessible options out of the box."
- I think this code https://github.com/humhub/humhub-prosemirror/blob/master/src/editor/core/plugins/anchors/index.js#L29 `permalink: true` should be updated to something like this `permalink: markdown_it_anchor_plugin.permalink.headerLink()`

---

How it is broken now:

![develop-missed-anchor](https://github.com/humhub/wiki-2.0-issues/assets/6995524/c4169610-8f4e-4027-b41c-f4b5401cc757)

---

Expected result on render header:

![master-anchor](https://github.com/humhub/wiki-2.0-issues/assets/6995524/483ab7b9-095d-4b56-94e2-391384d893ab)

**Comment by yuriimaz** [comment]
@luke- Can you explain what exactly had to be entered before so that a similar title with an anchor appeared?

**Comment by luke-** [comment]
@yurabakhtin Can you please help here?

**Comment by yurabakhtin** [comment]
@yuriimaz 

- Create any Wiki page with content like from my screenshot below,
- Test it on the branch `master` v1.14.3, you should find an anchor on over mouse,
- Switch to the branch `develop` v1.15.0 (don't forget to run `composer install` from root), you see the anchors are lost for the headers,
- I guess the problem as I decscribed here https://github.com/humhub/humhub-prosemirror/issues/113#issue-1813542736

![test-header-anchors](https://github.com/humhub/humhub-prosemirror/assets/6995524/bfb4edc9-13ee-4ac9-b0b3-a0c9333f9faa)

**Comment by yuriimaz** [comment]
@luke- I still don't understand. What exactly should be entered in the editor so that after saving we get the expected look of the title with an anchor?

**Comment by yuriimaz** [comment]
@yurabakhtin Is just the text enough to make the header?

**Comment by luke-** [comment]
> @luke- @yurabakhtin I still don't understand. What exactly should be entered in the editor so that after saving we get the expected look of the title with an anchor?

Try to create some "headline 1" elements.

**Comment by yurabakhtin** [comment]
@yuriimaz

> I still don't understand. What exactly should be entered in the editor so that after saving we get the expected look of the title with an anchor?

![headers](https://github.com/humhub/humhub-prosemirror/assets/6995524/e1e46526-69c1-40c4-9280-6f45a25f2dba)

Just try to create a Wiki page with some random text then apply "Heading 1" or "Heading 2" to the text, so an expected result is that text should be rendered as `<h1 id="header-text">Header text<a href="#header-text">...</a></h1>` but wrong result is `<h1>Header text</h1>`, please find more details on my screenshots and in the investigation above, or please ask me more details if you cannot reproduce the bug on the `develop v1.15.0`(don't forget to refresh by `composer install` when you switch between branches `master` and `develop`).

**Comment by yuriimaz** [comment]
@yurabakhtin @luke- Tanks. I can already see it, I'm trying to fix it.

**Comment by luke-** [comment]
Related: https://github.com/humhub/humhub-prosemirror/issues/115
