### ISSUE TITLE
CodeMirror - Leave editor with Arrow/Up Down 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-prosemirror#116]
Steps to reproduce:

- Add a "Code" inside an empty Prosemirror editor 
- It's not possible to create other elements (e.g. regular text) above or below the editor

In other elements like the "block quote" it's possible to "escape" with arrow up or arrow down keys.

**Comment by yuriimaz** [comment]
@luke- Despite the fact that there is already a special key combination Ctrl+Enter to go to the next pargraph from the codemirror block, I added the same option for the right and down arrows. You can move up or left if there are other blocks at the top, just like for blockquotes
