### ISSUE TITLE
Code Mirror - Toolbar "Horizontal Rule" available

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-prosemirror#117]
When inside a Code (Mirror) block, the "insert horizontal rule" option is active. This shouldn't be available. Or is there a reason for it?

e.g.
![image](https://github.com/humhub/humhub-prosemirror/assets/4736168/dc3fd8b1-b818-41a6-a3ae-a295f8afaf3d)

**Comment by yuriimaz** [comment]
@luke- I checked and it turned out to be quite convenient - without leaving the block of code, immediately insert a horizontal line under it. I think we can leave this functionality as the author intended.
