### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Gizmotronn** [humhub/humhub-prosemirror#12]
Hey, I'm really interested in using Humhub, and I'm trying to learn more about it. I use a content editor called "prose" for my jekyll site, and I'm wondering what prosemirror is. There's no documentation on this repo and any search on google doesn't give me a result

Delete if not allowed

**Comment by buddh4** [comment]
Check [https://prosemirror.net/](https://prosemirror.net/) for more information. The HumHub richtext is based upon prosemirror and adds some features as a plugin system and some HumHub specific core plugins. 

Basically prosemirror provides a schema abstraction for your editor. The schema for example could be based on markdown (which is the case in HumHub) or json format. The schema defines all available node (e.g. headline) and mark  (e.g. bold text) types and how parse from or translate to your base format. I'am sure this is explained way more clearly in the prosemirror documentation ;)

Example for bold text mark:

```javascript
const schema = {
    marks: {
        strong: {
            sortOrder: 200,
            parseDOM: [{tag: "b"}, {tag: "strong"},
                {
                    style: "font-weight", getAttrs: function (value) {
                    return /^(bold(er)?|[5-9]\d{2,})$/.test(value) && null;
                }
                }],
            toDOM: () => {
                return ["strong"]
            },
            parseMarkdown: {mark: "strong"},
            toMarkdown: {open: "**", close: "**", mixable: true, expelEnclosingWhitespace: true}
        }
    }
};
```

Here you have two examples of custom plugin extensions:

- [Wiki](https://github.com/humhub/humhub-modules-wiki/blob/master/resources/js/humhub.wiki.linkExtension.js)
- [Underline](https://github.com/humhub-contrib/devtools/blob/master/views/showcase/tabs/richtext_custom_preset/try.php#L23)
