### ISSUE TITLE
Add intuitive list intend

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub-prosemirror#13]
Humhub 1.4

It would be great to be able to write this in Humhub :
- First level
  - Second level (indented item)
  - Second level (indented item)
- First level

**Comment by ArchBlood** [comment]
@buddh4 manual input rules do apply to some point, sometimes it requires me to manually edit the post and add a new blank line to work.

### [Example](https://community.humhub.com/content/perma?id=213398)
![Screenshot_2](https://user-images.githubusercontent.com/35392110/78404333-2f908500-75cc-11ea-905c-0dd28a5502ee.png)

**Comment by funkycram** [comment]
What we need is something intuitive and commonly used.
Example : with Google docs, you have these 2 buttons to change level : 
![image](https://user-images.githubusercontent.com/23310825/78404795-68961d00-75ff-11ea-8d9e-509a2b2b2a0e.png)

**Comment by Oremountainflorian** [comment]
> Just click again on the list menu item, think this is currently not possible by input rule, perhaps we should add intend by `tab`

@buddh4 This will definitely solve the problem! We're all used to intend to the right by clicking `tab` and going back left by clicking `shift+tab`. 

From my experience: We work with more than 60 people in HumHub and I guess merely 5 know how to use 2nd or more level indent... Even if it works well once you know how it goes with

- `-` + `whitespace` + text
  - `Enter` + `←` + `-` + `whitespace` + text
    - `Enter` + `←` + `-` + `whitespace` + text
  - `Enter` + `Enter`
- `Enter` + `Enter`

people get frustrated. And @ArchBlood you're right, sometimes just a blank line works^^

By the way thank you really much for fixing the issue, that ![image](https://user-images.githubusercontent.com/44228345/78643725-fcdcda00-78b4-11ea-81e9-698e8fe5bf7f.png)now doesn't disappear anymore, this makes it handier, but yet not perfect.

**Comment by acheype** [comment]
I agree, as a developer, it took me a long time to figure out how these chips work...

The other thing in the editor that seems counter-intuitive to me is that you have to systematically skip 2 lines before you can change the paragraph style.
For example, to put a paragraph in quotation, if you only skip one line you also put the whole previous paragraph in quotation.

**Comment by buddh4** [comment]
I've opened an overview issue to assemble some richtext usability issues, hope we can fix as many issues in version 1.7. Feel free to add other usability related issues: https://github.com/humhub/humhub/issues/4215

**Comment by buddh4** [comment]
Added indent/dedent menu items in https://github.com/humhub/humhub-prosemirror/commit/de867cdfe5d27f8818cacce474c328dbe4d15c2e the problem with tab support is mainly that it breaks accessibility and form navigation.
