### ISSUE TITLE
Disable menu bar not working

### ISSUE THREAD

**Issue by purtisolano** [humhub/humhub-prosemirror#14]
I'm sorry if I don't get it right but it seems like on the line 62689 says that setting 'menuBar = false' will disable this element. It doesn't seem to work.

Could it be that it is not implemented in the function?

Thank you very much for this fantastic functionality,

This version of 'setupPlugins' function seems to work.

`function setupPlugins(context) {
            var result = buildPluginKeymap(context);

            result = result.concat([
                buildInputRules(context),
                keymap(buildKeymap(context)),
                keymap(baseKeymap),
                dropCursor(),
                gapCursor(),
                dist_1(),
            ]);

            if (context.options.menuBar !== false) {
                result.push(buildMenuBar(context));
            }

            result.push(
              keymap({
                "Tab": dist_41(1),
                "Shift-Tab": dist_41(-1)
              })
            );

            if (context.options.history !== false) {
                result.push(history());
            }

            return result.concat(buildPlugins(context));
        }`

**Comment by buddh4** [comment]
I'am currently working on a proper menu configuration for HumHub 1.9 (https://github.com/humhub/humhub-prosemirror/issues/48). Which item do you want to hide?
