### ISSUE TITLE
Add option to open links in same or new tab

### ISSUE THREAD

**Issue by Oremountainflorian** [humhub/humhub-prosemirror#15]
### Description

At the moment links created with the editor open in a new browser tab by default. This is the preferable way in most scenarios, but there might be others. 

### Solution

Add a checkbox "Open in new tab" below the title field with tick set by default. 

![image](https://user-images.githubusercontent.com/44228345/78657926-c2316c80-78c9-11ea-8caf-da157a94ada7.png)

**Comment by luke-** [comment]
Related: https://github.com/humhub/humhub-prosemirror/pull/78
