### ISSUE TITLE
Deleting comment after mentioning dups last name

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub-prosemirror#16]
When mentioning someone then trying to delete text it dups the user's last name every time you use the backspace button to delete on mobile.

**Comment by ArchBlood** [comment]
Duplicated on community site when PWA is installed

**Comment by buddh4** [comment]
Bug issues should rather be opened on github, so If this is still an issue, either reopen the issue here or on humhub core.

**Comment by ArchBlood** [comment]
Issue was fixed in one of the betas it looks like :thinking:
