### ISSUE TITLE
Links in Code block leaks Markdown syntax

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub-prosemirror#17]
Reported here: https://community.humhub.com/s/general-discussion/?contentId=217114
Reproduced here: https://community.humhub.com/u/ArchBlood/?contentId=217128

**Comment by buddh4** [comment]
You mean links in inline code like `this` ?

**Comment by joeworkman** [comment]
If you look at the linked post above, you will see that its a code block 

```
https://www.weavers.space/stacks/
```

shows up like this

```
[https://www.weavers.space/stacks/](https://www.weavers.space/stacks/)
```

**Comment by Oremountainflorian** [comment]
Hm for me it works fine with HumHub 1.5.1 and PHP 7.3.17 on Firefox 76 

## Comment ↓
![Prosemirror_comment](https://user-images.githubusercontent.com/44228345/82089630-43172b80-96f4-11ea-9aa1-8901d55552a3.PNG)

![Prosemirror_comment2](https://user-images.githubusercontent.com/44228345/82089639-44485880-96f4-11ea-8db6-812697558a04.PNG)

## Wiki ↓
![Prosemirror_comment3](https://user-images.githubusercontent.com/44228345/82089642-46121c00-96f4-11ea-9c00-5026f1de30f6.PNG) 

![Prosemirror_comment4](https://user-images.githubusercontent.com/44228345/82089646-46aab280-96f4-11ea-87b8-cfafd0ad6af7.PNG)

Playing around with the wiki I found a **minor bug**: On the 3rd picture it isn't possible to go to a new line at the bottom of the document with the cursor inside a quote block (at least it didn't find out how after 2 min...)

**Comment by buddh4** [comment]
The link issue does only occure in cide blocks, not quotes, the other issue should also be fixed with 1.5.2 but i'll test again

**Comment by ArchBlood** [comment]
I can confirm that 1.5.1 through the community this is an issue for PHP 7.x

### Example
1. Add test then make that text a hyperlink via the richtext buttons after hightlight and click the code block button and submit the post
2. Create a code block then add text and make this text a hyperlink all via the richtext buttons and submit the post.

**Comment by buddh4** [comment]
This was an core issue fixed by https://github.com/humhub/humhub/commit/83bc56af65ff52bc218193ed7202427bacfc1230
