### ISSUE TITLE
Richtext overlay breaks native copy & paste overlay

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub-prosemirror#20]
When trying to copy & paste the overlay of the Richtext makes it almost impossible to copy & paste on Android & iOS for all stable versions that include ProseMirror

**Comment by buddh4** [comment]
Which overlay are you refering to, the menu?

**Comment by ArchBlood** [comment]
When copy/pasting text natively this works as intended, the issue is that the native menu when highlighting text it gets in the way of the editor menu and forces you to scroll till it's no longer visible for a few seconds to use the editor menu options, this happens in all versions that include the RichText editor

**Comment by buddh4** [comment]
Ok, so you mean its the other way around, that the native overlay breaks the usability of the menu. This is a known issue with such menus on mobile:

- https://github.com/ProseMirror/prosemirror/issues/7

The only solutions I see for now is:

- Add menu to bottom on mobile
- Some kind of javascript magic if the selection starts in the first few lines

**Comment by ArchBlood** [comment]
> Ok, so you mean its the other way around, that the native overlay breaks the usability of the menu. This is a known issue with such menus on mobile:
> 
> * [ProseMirror/prosemirror#7](https://github.com/ProseMirror/prosemirror/issues/7)
> 
> The only solutions I see for now is:
> 
> * Add menu to bottom on mobile
> * Some kind of javascript magic if the selection starts in the first few lines

I believe the first option would probably be much easier, although not sure if it would be the most eye pleasing option :thinking:
