### ISSUE TITLE
Add possibility to hide toolbar menu entries by CSS

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-prosemirror#24]
It would be good if the various menu entries had a unique class name so that they could be hidden.

![image](https://user-images.githubusercontent.com/4736168/102211092-6648ca00-3ed3-11eb-9daa-84dacfdab6d5.png)

As a specific use case, this would be good for the images Option or Headline 3-7, for example.

**Comment by buddh4** [comment]
I think its better do exclude them not by css and rather by configuration. Also you may don't want to hide a menu item in all editors, e.g. only in post/comment but not in the wiki.

**Comment by luke-** [comment]
A context-dependent configuration would of course be the best solution. Is this planned for 1.8?

**Comment by buddh4** [comment]
@luke- yes
