### ISSUE TITLE
Editor Scrolling Broken in Android Chrome

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub-prosemirror#25]
### What steps will reproduce the problem?

Paste a large block of text into a new post.  Attempt to pull down (to scroll up and edit).

### What is the expected result?

Text input should be scrollable.

### What do you get instead?

Chrome pull-to-reload destroys all input.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version      | 7.4.3
| Operating system | Ubuntu 20

**Comment by buddh4** [comment]
This may be fixed in HumHub 1.8.0, I've removed the usage of nicescroll on small devices in the richtext. Can you confirm this?

**Comment by buddh4** [comment]
In my tests it worked with HumHub 1.8.0

**Comment by miqrogroove** [comment]
Fixed for me as well.  Thank you.
