### ISSUE TITLE
Copy Paste Lists broken

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-prosemirror#26]
e.g. Copy a list e.g. PHPStorm
![image](https://user-images.githubusercontent.com/4736168/105362177-da753c80-5bfa-11eb-9364-3f0408348928.png)

Paste it to the editor

![image](https://user-images.githubusercontent.com/4736168/105362228-eeb93980-5bfa-11eb-861e-3d0f20d43de9.png)

**Comment by buddh4** [comment]
This is not a problem with the editor, phpstorm copies the text as code, see https://intellij-support.jetbrains.com/hc/en-us/community/posts/206176309-Disable-rich-text-copying-
