### ISSUE TITLE
Add Build/Package/Release Documentation

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-prosemirror#28]
It would be good to have some information on the build and release process.

**Comment by buddh4** [comment]
https://github.com/humhub/humhub-prosemirror

Regarding release:

- Update version in package.json
- Login:

```
npm login
```

- Publish:

```
npm publish
```

**Comment by luke-** [comment]
@buddh4 Thanks. Is there anything against also include the release steps to  the Readme.MD, then we have everything in one place?

**Comment by buddh4** [comment]
Hmm, should be basic knowledge for anyone who maintains npm packages, not sure if this belongs to a readme.

**Comment by luke-** [comment]
Okay, let's leave it out then.
