### ISSUE TITLE
Tabulator Support

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-prosemirror#30]
Would be great to have Tabulator support inside of Code Areas (similar to CodeMirror).

**Comment by buddh4** [comment]
Yes would be great, but we have to to think about a right key mapping for this since `tab` should not be overwritten in order to enable keyboard navigation especially for accessibility reasons.

**Comment by buddh4** [comment]
https://twitter.com/MarijnJH/status/1319268127780294656

**Comment by buddh4** [comment]
Maybe we could init a codemirror editor within an extra modal when clicking on a code block.

**Comment by luke-** [comment]
It would be also good if you could open a new level within a list e.g. `ul` using <tab>.

**Comment by luke-** [comment]
@yuriimaz Thanks works very good!
