### ISSUE TITLE
Copy&Paste: Link lost

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-prosemirror#44]
**To reproduce:**

- Create a link
- Copy/Cut & Paste -> Link is lost, but text is copied

**Comment by buddh4** [comment]
Cannot reproduce this. Does this only happen for special links e.g. wiki?

**Comment by luke-** [comment]
Too reproduce on e.g. our Community:

1.) Open Richtext (e.g. Post Create Form)
2.) Write "Test"
3.) Mark "Test", click Link Icon, link to "https://google.com"
4.) A Link appears in the Editor
5.) Select the word "Test"
6.) Strg+X
7.) Strg+V
 
The Link is lost

**Comment by buddh4** [comment]
Ok, seems only to happen with manually marked links, not if the link was pasted into the richtext.
