### ISSUE TITLE
Edit code block in codemirror

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub-prosemirror#47]
Add edit button to code blocks, which opens a codemirror editor on top. With the ability to change code block language (if allowed by config)

**Comment by luke-** [comment]
https://prosemirror.net/examples/codemirror/

**Comment by yuriimaz** [comment]
@luke- I tried to add the use of codemirror in three ways (including the official one). But I never managed to build the module after integration due to build errors related to codemiror packages. So I returned the task to TODO
