### ISSUE TITLE
@ becomes @@ when copying mentioning in wiki editor

### ISSUE THREAD

**Issue by Oremountainflorian** [humhub/humhub-prosemirror#59]
## System

HumHub 1.5.1.
PHP 7.3.17
Wiki 1.3.13

## Problem description 

When you copy/cut a mentioning ("@..") in the editor (wiki page/comment/...) and paste it turns to an ("@@.."). Once it's saved, it's returns to be an single "@..", in a saved page as well as in edit mode again. The mentioning still works then. 

![grafik](https://user-images.githubusercontent.com/44228345/82117159-bbbace00-976e-11ea-9de3-20e86c64e5aa.png)

⬇️ Save

![grafik](https://user-images.githubusercontent.com/44228345/82117164-cbd2ad80-976e-11ea-82f8-e3eb1306a1e0.png)

⬇️ Edit again

![grafik](https://user-images.githubusercontent.com/44228345/82117190-f02e8a00-976e-11ea-871e-589ca1468134.png)

**Further observation 1** When it's copied from comment edit mode to wiki page edit mode you can copy it several times without creating redundant "@"s. **Doesn't work vice versa**

**Further observation 2** Works fine when the mentioning is copied from saved comment (stream/wiki) or saved wiki page to arbitrary edit mode, then you can copy it several times without creating redundant "@"s

**Comment by luke-** [comment]
@yuriimaz Can you please try to reproduce?

**Comment by yuriimaz** [comment]
@luke- Yes, I was able to reproduce this and it is a completely logical behavior during such actions with mentions in the richtext editor. I'll try to add a safeguard to correctly paste the copied mention text from the buffer.
