### ISSUE TITLE
Text edition toolbar: move the "Upload File" item from image dropdown menu to an icon in the toolbar

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub-prosemirror#66]
Problem: people do not find where to attach a file in the richtext editor.
You need to click on the "image" icon. This is not intuitive, and people think you can only attach images files.

Suggestion: remove the "Upload File" item menu and add an icon directly in the toolbar: https://fontawesome.com/v4.7/icon/paperclip or https://fontawesome.com/v4.7/icon/cloud-upload

**Comment by samuk** [comment]
+1 I've also had feedback this UX is poor

More:
https://community.humhub.com/s/general-discussion/?contentId=254633&commentId=41473

**Comment by arisudi** [comment]
How to remove Upload File button from the editor?

**Comment by samuk** [comment]
+1 I'd be interested if there are any plans overall to improve the UX of the editor.

**Comment by turbostas1** [comment]
This is very bad and needs to be fixed asap. The best would be to have separate buttons for Insert Image, Insert File and Insert Ruler. Alternatively insert button with Image, File and Ruler in the dropdown. 

Insert File should open finder window showing all compatible image files for insertion. Right now Insert Image button opens formatting window for an image.

**Comment by marc-farre** [comment]
Done and available in HumHub 1.16
