### ISSUE TITLE
"Send" and "Add File" buttons layout should be improved

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub-prosemirror#83]
"Send" and "Add File" buttons are located on the right side of input text area.
This make the **text area too narrow** in a 3 columns page
![image](https://user-images.githubusercontent.com/91057837/218253747-7906c97a-edca-45fa-bb10-7a463a85dd2f.png)

And the editor long menubar needs 2 rows.
![image](https://user-images.githubusercontent.com/91057837/218253802-7bf18b49-d137-4fa1-b676-0b93da837ddd.png)

Should be improved. 

Please Have a look [to how it works in our HH site](https://drive.google.com/file/d/1WR7l5ck3JbQlNSww-sEJ9L8v_lh2-uGm/view?usp=sharing),(video - 1 minute) thanks to some additionnal JS and CSS in a custom theme.
You will notice that **"Send" and "Add File" buttons are hidden most of the time** and will be displayed below the text field, and only when needed (this also makes the page "cleaner").

**Comment by marc-farre** [comment]
@Gilbertdelyon In Humhub 1.15 this has been improved.
If you think it's OK now, you can close this issue.

**Comment by Gilbertdelyon** [comment]
@marc-farre 
Nearly well made !
Not as well as in [ our tsite ](https://drive.google.com/file/d/1WR7l5ck3JbQlNSww-sEJ9L8v_lh2-uGm/view?usp=sharing),(video - 1 minute)
But you are right, we can close this issue

**Comment by Gilbertdelyon** [comment]
closed
